# Generated by Django 3.0 on 2023-06-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='name')),
                ('mobile', models.IntegerField(max_length=32, verbose_name='mobile phone')),
                ('email', models.CharField(max_length=32, verbose_name='email')),
                ('age', models.IntegerField(verbose_name='age')),
                ('subscribe', models.BooleanField(default=False)),
            ],
        ),
    ]
