# Generated by Django 3.0 on 2023-06-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default=111, max_length=64, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.IntegerField(verbose_name='mobile phone'),
        ),
    ]
