# Generated by Django 3.0 on 2023-06-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230613_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.IntegerField(max_length=64, verbose_name='mobile phone'),
        ),
    ]
