# Generated by Django 3.0 on 2023-06-13 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='ContentLevel',
        ),
    ]
