# Generated by Django 3.0 on 2023-06-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20230613_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentlevel',
            old_name='lever',
            new_name='level',
        ),
    ]
