# Generated by Django 3.0 on 2023-06-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230615_0058'),
        ('content', '0003_auto_20230613_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('what_area', models.CharField(max_length=2000, verbose_name='what_area')),
                ('how_area', models.CharField(max_length=2000, verbose_name='how_area')),
                ('try_area', models.CharField(max_length=1000, verbose_name='try_area')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserInfo', verbose_name='author')),
            ],
        ),
    ]
