# Generated by Django 3.0 on 2023-06-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_newcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcontent',
            name='example',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='example_area'),
        ),
        migrations.AddField(
            model_name='newcontent',
            name='source',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='source_area'),
        ),
        migrations.AlterField(
            model_name='newcontent',
            name='how_area',
            field=models.CharField(max_length=3000, verbose_name='how_area'),
        ),
        migrations.AlterField(
            model_name='newcontent',
            name='try_area',
            field=models.CharField(max_length=3000, verbose_name='try_area'),
        ),
        migrations.AlterField(
            model_name='newcontent',
            name='what_area',
            field=models.CharField(max_length=3000, verbose_name='what_area'),
        ),
    ]
