# Generated by Django 3.0 on 2023-06-21 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20230622_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcontent',
            name='example',
        ),
    ]
