# Generated by Django 3.0 on 2023-06-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_newcontent_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcontent',
            name='example',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='example_area'),
        ),
    ]
