# Generated by Django 3.0 on 2023-06-21 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230615_0058'),
        ('content', '0007_newcontent_example'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewContent',
            new_name='NewContents',
        ),
    ]
