# Generated by Django 3.0 on 2023-06-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20230622_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcontent',
            name='classification',
            field=models.CharField(default='Fundamentals of Machine Learning', max_length=500, verbose_name='classification'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newcontent',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='title'),
        ),
    ]
