# Generated by Django 4.2.4 on 2023-08-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20230629_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='level_lable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1', models.CharField(max_length=1000, verbose_name='level1')),
                ('level2', models.CharField(max_length=1000, verbose_name='level2')),
            ],
        ),
        migrations.CreateModel(
            name='NewCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('level1', models.CharField(max_length=100, verbose_name='level1')),
                ('level2', models.CharField(max_length=100, verbose_name='level2')),
                ('contents', models.CharField(max_length=3000, verbose_name='what_area')),
                ('contents1', models.CharField(max_length=3000, verbose_name='what_area')),
                ('source', models.CharField(blank=True, max_length=300, null=True, verbose_name='source_area')),
            ],
        ),
    ]
